steps:
  - name: 'node:10.16.3'
    entrypoint: 'yarn'
    dir: 'functions'
    args: ['install']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    entrypoint: 'npm'
    dir: 'functions'
    args: ['rebuild']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args:
      [
        'deploy',
        '--only',
        'functions:trigger',
        '--debug',
        '--project',
        '${_FIREBASE_PROJECT_ID}',
      ]
    timeout: 600s
    env:
      - 'FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}'
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - 'FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - 'DEPLOY_ID_TO_NUXT=${_DEPLOY_ID_TO_NUXT}'
      - 'DEPLOY_ID_TO_FUNCTIONS=${_DEPLOY_ID_TO_FUNCTIONS}'
      - 'BASE_URL=${_BASE_URL}'
