runtime: nodejs10
instance_class: F2
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always
  - url: /(.*\.(gif|png|jpg|ico|txt|js|svg))$
    static_files: src/static/\1
    upload: src/static/.*\.(gif|png|jpg|ico|txt|js|svg)$
    secure: always
  - url: /.*
    script: auto
    secure: always
env_variables:
  NUXT_HOST: '0.0.0.0'
  NUXT_PORT: '8080'
